AWSTemplateFormatVersion: '2010-09-09'
Description: Elastic Beanstalk deployment stack for Data Onboarding Framework

Parameters:
  ApplicationName:
    Type: String
    Default: DataOnboardingApp
    Description: Elastic Beanstalk application name
  EnvironmentName:
    Type: String
    Default: DataOnboardingEnv
    Description: Base name for Elastic Beanstalk environments
  InstanceType:
    Type: String
    Default: t3.small
    Description: EC2 instance type
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 KeyPair for SSH access
  DeployEnvironment:
    Type: String
    AllowedValues:
      - dev
      - qa
      - prod
    Description: Environment to deploy

Conditions:
  IsDev: !Equals [ !Ref DeployEnvironment, dev ]
  IsQA: !Equals [ !Ref DeployEnvironment, qa ]
  IsProd: !Equals [ !Ref DeployEnvironment, prod ]

Resources:
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ServiceRole

  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName
      Description: Data Onboarding Framework application

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ApplicationName}-eb-artifacts-${AWS::AccountId}'

  InitialVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref Application
      VersionLabel: initial
      SourceBundle:
        S3Bucket: !Ref S3Bucket
        S3Key: initial.zip

  EnvironmentDev:
    Condition: IsDev
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      EnvironmentName: !Sub '${EnvironmentName}-dev'
      ApplicationName: !Ref Application
      PlatformArn: arn:aws:elasticbeanstalk:${AWS::Region}::platform/Python 3.8 running on 64bit Amazon Linux 2
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref InstanceType
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile

  EnvironmentQA:
    Condition: IsQA
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      EnvironmentName: !Sub '${EnvironmentName}-qa'
      ApplicationName: !Ref Application
      PlatformArn: arn:aws:elasticbeanstalk:${AWS::Region}::platform/Python 3.8 running on 64bit Amazon Linux 2
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref InstanceType
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile

  EnvironmentProd:
    Condition: IsProd
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      EnvironmentName: !Sub '${EnvironmentName}-prod'
      ApplicationName: !Ref Application
      PlatformArn: arn:aws:elasticbeanstalk:${AWS::Region}::platform/Python 3.8 running on 64bit Amazon Linux 2
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref InstanceType
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile

Outputs:
  DevEnvURL:
    Description: URL of dev Elastic Beanstalk environment
    Value: !GetAtt EnvironmentDev.EndpointURL
  QAEnvURL:
    Description: URL of qa Elastic Beanstalk environment
    Value: !GetAtt EnvironmentQA.EndpointURL
  ProdEnvURL:
    Description: URL of prod Elastic Beanstalk environment
    Value: !GetAtt EnvironmentProd.EndpointURL