AWSTemplateFormatVersion: '2010-09-09'
Description: Elastic Beanstalk deployment stack for Data Onboarding Framework

Parameters:
  ApplicationName:
    Type: String
    Default: dataonboardingapp
    AllowedPattern: '^[a-z0-9-]+$'
    ConstraintDescription: 'Must be lowercase letters, numbers, and hyphens only'
  EnvironmentName:
    Type: String
    Default: DataOnboardingEnv
  InstanceType:
    Type: String
    Default: t3.small
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  DeployEnvironment:
    Type: String
    AllowedValues:
      - dev
      - qa
      - prod
    Default: dev
  SolutionStackName:
    Type: String
    Default: "64bit Amazon Linux 2023 v4.5.1 running Python 3.11"
    Description: EB platform solution stack name (e.g. 64bit Amazon Linux 2023 v4.5.1 running Python 3.11)
  SourceBundleKey:
    Type: String
    Default: app.zip
    Description: S3 key of the application bundle in the artifacts bucket
  VersionLabel:
    Type: String
    Default: "initial-version"
    Description: Version label for the Elastic Beanstalk application version

Resources:
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: SecretManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ !Ref ServiceRole ]

  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref ApplicationName
      EnvironmentName: !Ref EnvironmentName
      SolutionStackName: !Ref SolutionStackName
      VersionLabel: !Ref VersionLabel
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref InstanceType
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: LoadBalancerType
          Value: application
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: LOG_FILE
          Value: /var/log/app.log
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: PORT
          Value: 8000

Outputs:
  EnvURL:
    Value: !GetAtt Environment.EndpointURL
  EnvironmentName:
    Description: "Elastic Beanstalk environment name"
    Value: !Ref EnvironmentName