AWSTemplateFormatVersion: '2010-09-09'
Description: Elastic Beanstalk deployment stack for Data Onboarding Framework

Parameters:
  ApplicationName:
    Type: String
    Default: dataonboardingapp
    AllowedPattern: '^[a-z0-9-]+$'
    ConstraintDescription: 'Must be lowercase letters, numbers, and hyphens only'
  EnvironmentName:
    Type: String
    Default: DataOnboardingEnv
  InstanceType:
    Type: String
    Default: t3.small
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

  DeployEnvironment:
    Type: String
    AllowedValues:
      - dev
      - qa
      - prod
    Default: dev

Resources:
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ !Ref ServiceRole ]

  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ApplicationName}-eb-artifacts-${DeployEnvironment}'

  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      EnvironmentName: !Ref EnvironmentName
      ApplicationName: !Ref Application
      SolutionStackName: "64bit Amazon Linux 2 v3.3.14 running Python 3.8"
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref InstanceType
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: LOG_FILE
          Value: /var/log/app.log

Outputs:
  EnvURL:
    Value: !GetAtt Environment.EndpointURL
  S3BucketName:
    Description: Name of the S3 bucket for EB artifacts
    Value: !Sub '${ApplicationName}-eb-artifacts-${DeployEnvironment}'