name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials for Dev
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          aws-region: us-east-1

      - name: Configure AWS credentials for QA
        if: ${{ github.ref == 'refs/heads/qa' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_QA }}
          aws-region: us-east-1

      - name: Configure AWS credentials for Prod
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
          aws-region: us-east-1

      - name: Set variables
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [[ "$BRANCH" == "main" ]]; then ENV=prod; else ENV=$BRANCH; fi
          STACK_NAME="DataOnboarding-${ENV}"
          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "STACK_NAME=$STACK_NAME" >> $GITHUB_ENV

      - name: Create CFN artifacts bucket
        run: |
          aws s3 mb s3://dataonboardingapp-cfn-artifacts-${ENV} || true

      - name: Package CloudFormation
        run: |
          aws cloudformation package \
            --template-file infra/cloudformation.yaml \
            --s3-bucket dataonboardingapp-cfn-artifacts-${ENV} \
            --output-template-file packaged.yaml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name ${STACK_NAME} \
            --parameter-overrides file://infra/parameters/${ENV}-parameters.json \
            --query 'Stacks[0].Outputs[?OutputKey==`S3BucketName`].OutputValue' \
            --output text)
          echo "EB_S3_BUCKET=${S3_BUCKET}" >> $GITHUB_ENV

      - name: Archive application
        run: zip -r app.zip . -x "**/.git*" "**/.github/*"

      - name: Upload artifact to S3
        run: |
          S3_KEY="app_${GITHUB_SHA}.zip"
          aws s3 cp app.zip s3://${EB_S3_BUCKET}/${S3_KEY}
          echo "S3_KEY=${S3_KEY}" >> $GITHUB_ENV

      # Deploy application version via CloudFormation
      - name: Deploy application via CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file infra/cloudformation.yaml \
            --stack-name ${STACK_NAME} \
            --parameter-overrides file://infra/parameters/${ENV}-parameters.json SourceBundleKey=${S3_KEY} \

            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset