[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8000
address = "0.0.0.0"
maxUploadSize = 100

[global]
developmentMode = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8000