[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8000
address = "0.0.0.0"
maxUploadSize = 200

[global]
developmentMode = false

[browser]
gatherUsageStats = false
serverAddress = "${STREAMLIT_SERVER_ADDRESS}"
serverPort = 8000

[runner]
fastReruns = true
