[server]
port = 5000
# This will work as localhost on Windows and 0.0.0.0 on Elastic Beanstalk
address = "${STREAMLIT_SERVER_ADDRESS:-localhost}"
enableCORS = true
enableXsrfProtection = true

[browser]
serverAddress = "${STREAMLIT_SERVER_ADDRESS:-localhost}"
gatherUsageStats = false