[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8000
address = "0.0.0.0"
maxUploadSize = 200

[global]
developmentMode = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
fastReruns = true